Revert "chore(query-service): 🔧 include prefer-delta flag"
SigNoz/charts pull request #290
Opened 2023-09-17 05:36 UTC by srikanthccv

Reverts SigNoz/charts#287

I remembered why we don't want to have prefer-delta true in charts. For our customers, we need to have two pipelines - one each for delta and cumulative and let the data be populated for some time. Then, we remove the cumulative pipeline and set the prefer-delta to true. This is the smooth way to roll out this change: https://github.com/SigNoz/signoz/issues/3579. Otherwise, people won't be able to see data fully.

2023-09-17 05:37 UTC, srikanthccv commented
This should be fine for the main repo docker users, if there some users they can also follow this approach.

2023-09-18 14:46 UTC, prashant-shahi approved these changes

2023-09-18 14:46 UTC, prashant-shahi commented
@srikanthccv also, feel free to bump up the chart version

2023-09-18 14:46 UTC, prashant-shahi requested changes
@srikanthccv Feel free to bump up the chart version

2023-09-18 14:59 UTC, prashant-shahi commented
okay, got it.

LGTM

2023-09-18 14:59 UTC, prashant-shahi approved these changes

2023-09-18 15:04 UTC, merged