add nodePort feature to _helpers.tpl
SigNoz/charts pull request #76
Opened 2022-09-06 09:30 UTC by furkanpehli1

Hi,

We were facing issue when we defined otelCollector's service type as NodePort. We were desiring to add nodePort statically but it was assigned to ports dynamically. So I added feature with @canerturkaslan to the _helper.tpl as you can see from our commit. 

For example if you want to assign static nodePort you can give values.yaml like below:

```yaml
otelCollector:
  service:
    type: NodePort
  ports:
    otlp:
      nodePort: 30900
      targetPort: otlp
      protocol: TCP
```

2022-09-06 17:23 UTC, prashant-shahi requested changes
@furkanpehli1 The changes look good. However, I don't think the helper function is used currently for OtelCollector but only used for OtelCollector Metrics.

We will be reverting OtelCollector back to `Deployment` from `DaemonSet` along with it's previous behaviour, so your PR would make sense then.

Can you include `nodePort` in otelCollector in `values.yaml`? Good to merge after that.

Example:
```
ports:
  otlp:
    ...
    # -- Node port for OTLP gRPC
    nodePort: ""
    ...
```

2022-09-06 17:53 UTC, furkanpehli1 commented
Hi @prashant-shahi, thanks for review. I have a question before commit. Adding `nodePort` parameter in otelCollector in `values.yaml` only for otlp is enough? Or do you want me to add it for all services?

2022-09-06 18:02 UTC, prashant-shahi commented
@furkanpehli1 It would be much appreciated if you could add it to the all.

2022-09-07 05:45 UTC, prashant-shahi approved these changes
:shipit: LGTM

2022-09-07 05:56 UTC, merged